# Generated by Django 3.1.5 on 2021-01-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cl_idms_insights_sgmnt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.TextField(blank=None, default='')),
                ('province', models.TextField(blank=None, default='')),
                ('population', models.IntegerField(blank=None, default='')),
                ('year', models.TextField(blank=None, default='')),
            ],
        ),
    ]
