# Generated by Django 3.1.5 on 2021-01-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshbrd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cl_idms_insights_sgmnt',
            new_name='data_population',
        ),
    ]
